name: CreativeLimiter
version: 2.7
authors: [MLGEditz, MrWouter]
website: http://www.mlgeditz.nl
main: nl.mlgeditz.creativelimiter.CreativeLimiter
description: An easy to use plugin to handle staff abuse

commands:
  creativelimiter:
    description: CreativeLimiter command
    aliases: [cc, limiter, climiter]